### ISSUE TITLE
Detecting changes (caching)

### ISSUE THREAD

**Issue by Dids** [CtripCloud/docker-make#12]
Does dmake support any kind of caching/change detection when it comes to building and pushing the images?

I'm currently struggling trying to figure out how to only push images with dmake if they have changed, instead of always pushing, no matter what.

In my case, I've come up with a script for various different linux distros, which detects if new apt packages are available, and if so, it marks the images as dirty by removing them locally, then hands over the build & push process to dmake, which doesn't really work, as dmake pushes everything regardless of changes.

**Comment by Dids** [comment]
Would it be a good idea to simply use separate dmake config files, then run dmake with those if a new build & push is necessary?

**Comment by jizhilong** [comment]
Hi @Dids `docker-make` will not detect any building cache or image content change, that is `docker-engine`'s work.

**Comment by Dids** [comment]
Thanks, just making sure. :)
